export enum ActivityType {
	SIGN_UP = 'SIGN_UP',
	SIGN_IN = 'SIGN_IN',
	SIGN_OUT = 'SIGN_OUT',
	UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
	CREATE_TEAM = 'CREATE_TEAM',
	DELETE_TEAM = 'DELETE_TEAM',
	REMOVE_TEAM_MEMBER = 'REMOVE_TEAM_MEMBER',
	INVITE_TEAM_MEMBER = 'INVITE_TEAM_MEMBER',
	ACCEPT_INVITATION = 'ACCEPT_INVITATION',
	ADD_FILTER = 'ADD_FILTER'
}

export enum UserRole {
	OWNER = 'owner',
	MEMBER = 'member'
}
